/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

const metadata = {
    models: {
        todoList: {
            name: 'TodoList', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, name: {
                    name: "name",
                    type: "String",
                }, owner: {
                    name: "owner",
                    type: "User",
                    isDataModel: true,
                    backLink: 'todoLists',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "ownerId" },
                }, ownerId: {
                    name: "ownerId",
                    type: "String",
                    attributes: [{ "name": "@default", "args": [] }],
                    defaultValueProvider: $default$TodoList$ownerId,
                    isForeignKey: true,
                    relationField: 'owner',
                }, organization: {
                    name: "organization",
                    type: "Organization",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'todoLists',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "organizationId" },
                }, organizationId: {
                    name: "organizationId",
                    type: "String",
                    isOptional: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    defaultValueProvider: $default$TodoList$organizationId,
                    isForeignKey: true,
                    relationField: 'organization',
                }, todos: {
                    name: "todos",
                    type: "Todo",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'list',
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            }
            ,
        }
        ,
        todo: {
            name: 'Todo', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, title: {
                    name: "title",
                    type: "String",
                }, done: {
                    name: "done",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "value": false }] }],
                }, listId: {
                    name: "listId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'list',
                }, list: {
                    name: "list",
                    type: "TodoList",
                    isDataModel: true,
                    backLink: 'todos',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "listId" },
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            }
            ,
        }
        ,
        user: {
            name: 'User', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                }, name: {
                    name: "name",
                    type: "String",
                }, email: {
                    name: "email",
                    type: "String",
                }, emailVerified: {
                    name: "emailVerified",
                    type: "Boolean",
                }, image: {
                    name: "image",
                    type: "String",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                }, role: {
                    name: "role",
                    type: "String",
                    isOptional: true,
                }, banned: {
                    name: "banned",
                    type: "Boolean",
                    isOptional: true,
                }, banReason: {
                    name: "banReason",
                    type: "String",
                    isOptional: true,
                }, banExpires: {
                    name: "banExpires",
                    type: "DateTime",
                    isOptional: true,
                }, sessions: {
                    name: "sessions",
                    type: "Session",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, accounts: {
                    name: "accounts",
                    type: "Account",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, members: {
                    name: "members",
                    type: "Member",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, invitations: {
                    name: "invitations",
                    type: "Invitation",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, todoLists: {
                    name: "todoLists",
                    type: "TodoList",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'owner',
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, email: {
                    name: "email",
                    fields: ["email"]
                },
            }
            ,
        }
        ,
        session: {
            name: 'Session', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                }, expiresAt: {
                    name: "expiresAt",
                    type: "DateTime",
                }, token: {
                    name: "token",
                    type: "String",
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                }, ipAddress: {
                    name: "ipAddress",
                    type: "String",
                    isOptional: true,
                }, userAgent: {
                    name: "userAgent",
                    type: "String",
                    isOptional: true,
                }, userId: {
                    name: "userId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'sessions',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "userId" },
                }, activeOrganizationId: {
                    name: "activeOrganizationId",
                    type: "String",
                    isOptional: true,
                }, impersonatedBy: {
                    name: "impersonatedBy",
                    type: "String",
                    isOptional: true,
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, token: {
                    name: "token",
                    fields: ["token"]
                },
            }
            ,
        }
        ,
        account: {
            name: 'Account', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                }, accountId: {
                    name: "accountId",
                    type: "String",
                }, providerId: {
                    name: "providerId",
                    type: "String",
                }, userId: {
                    name: "userId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'accounts',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "userId" },
                }, accessToken: {
                    name: "accessToken",
                    type: "String",
                    isOptional: true,
                }, refreshToken: {
                    name: "refreshToken",
                    type: "String",
                    isOptional: true,
                }, idToken: {
                    name: "idToken",
                    type: "String",
                    isOptional: true,
                }, accessTokenExpiresAt: {
                    name: "accessTokenExpiresAt",
                    type: "DateTime",
                    isOptional: true,
                }, refreshTokenExpiresAt: {
                    name: "refreshTokenExpiresAt",
                    type: "DateTime",
                    isOptional: true,
                }, scope: {
                    name: "scope",
                    type: "String",
                    isOptional: true,
                }, password: {
                    name: "password",
                    type: "String",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            }
            ,
        }
        ,
        verification: {
            name: 'Verification', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                }, identifier: {
                    name: "identifier",
                    type: "String",
                }, value: {
                    name: "value",
                    type: "String",
                }, expiresAt: {
                    name: "expiresAt",
                    type: "DateTime",
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    isOptional: true,
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    isOptional: true,
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            }
            ,
        }
        ,
        organization: {
            name: 'Organization', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                }, name: {
                    name: "name",
                    type: "String",
                }, slug: {
                    name: "slug",
                    type: "String",
                    isOptional: true,
                }, logo: {
                    name: "logo",
                    type: "String",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                }, metadata: {
                    name: "metadata",
                    type: "String",
                    isOptional: true,
                }, members: {
                    name: "members",
                    type: "Member",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'organization',
                }, invitations: {
                    name: "invitations",
                    type: "Invitation",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'organization',
                }, todoLists: {
                    name: "todoLists",
                    type: "TodoList",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'organization',
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, slug: {
                    name: "slug",
                    fields: ["slug"]
                },
            }
            ,
        }
        ,
        member: {
            name: 'Member', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                }, organizationId: {
                    name: "organizationId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'organization',
                }, organization: {
                    name: "organization",
                    type: "Organization",
                    isDataModel: true,
                    backLink: 'members',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "organizationId" },
                }, userId: {
                    name: "userId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'members',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "userId" },
                }, role: {
                    name: "role",
                    type: "String",
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            }
            ,
        }
        ,
        invitation: {
            name: 'Invitation', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                }, organizationId: {
                    name: "organizationId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'organization',
                }, organization: {
                    name: "organization",
                    type: "Organization",
                    isDataModel: true,
                    backLink: 'invitations',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "organizationId" },
                }, email: {
                    name: "email",
                    type: "String",
                }, role: {
                    name: "role",
                    type: "String",
                    isOptional: true,
                }, status: {
                    name: "status",
                    type: "String",
                }, expiresAt: {
                    name: "expiresAt",
                    type: "DateTime",
                }, inviterId: {
                    name: "inviterId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'invitations',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "inviterId" },
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            }
            ,
        }
        ,
    }
    ,
    typeDefs: {
        auth: {
            name: 'Auth', fields: {
                userId: {
                    name: "userId",
                    type: "String",
                }, organizationId: {
                    name: "organizationId",
                    type: "String",
                    isOptional: true,
                }, organizationRole: {
                    name: "organizationRole",
                    type: "String",
                    isOptional: true,
                },
            }
            ,
        }
        ,
    }
    ,
    deleteCascade: {
        todoList: ['Todo'],
        user: ['TodoList', 'Session', 'Account', 'Member', 'Invitation'],
        organization: ['TodoList', 'Member', 'Invitation'],
    }
    ,
    authModel: 'Auth'
};
function $default$TodoList$ownerId(user: any): unknown {
    return user?.userId;
}

function $default$TodoList$organizationId(user: any): unknown {
    return user?.organizationId;
}
export default metadata;
