//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, ExpressionUtils } from "@zenstackhq/orm/schema";
const _schema = {
    provider: {
        type: "sqlite"
    },
    models: {
        TodoList: {
            name: "TodoList",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    default: ExpressionUtils.call("cuid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true
                },
                name: {
                    name: "name",
                    type: "String"
                },
                owner: {
                    name: "owner",
                    type: "User",
                    relation: { opposite: "todoLists", fields: ["ownerId"], references: ["id"], onDelete: "Cascade", hasDefault: true }
                },
                ownerId: {
                    name: "ownerId",
                    type: "String",
                    default: ExpressionUtils.member(ExpressionUtils.call("auth"), ["userId"]),
                    foreignKeyFor: [
                        "owner"
                    ]
                },
                organization: {
                    name: "organization",
                    type: "Organization",
                    optional: true,
                    relation: { opposite: "todoLists", fields: ["organizationId"], references: ["id"], onDelete: "Cascade", hasDefault: true }
                },
                organizationId: {
                    name: "organizationId",
                    type: "String",
                    optional: true,
                    default: ExpressionUtils.member(ExpressionUtils.call("auth"), ["organizationId"]),
                    foreignKeyFor: [
                        "organization"
                    ]
                },
                todos: {
                    name: "todos",
                    type: "Todo",
                    array: true,
                    relation: { opposite: "list" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Todo: {
            name: "Todo",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    default: ExpressionUtils.call("cuid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true
                },
                title: {
                    name: "title",
                    type: "String"
                },
                done: {
                    name: "done",
                    type: "Boolean",
                    default: false
                },
                listId: {
                    name: "listId",
                    type: "String",
                    foreignKeyFor: [
                        "list"
                    ]
                },
                list: {
                    name: "list",
                    type: "TodoList",
                    relation: { opposite: "todos", fields: ["listId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        User: {
            name: "User",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true
                },
                name: {
                    name: "name",
                    type: "String"
                },
                email: {
                    name: "email",
                    type: "String",
                    unique: true
                },
                emailVerified: {
                    name: "emailVerified",
                    type: "Boolean",
                    default: false
                },
                image: {
                    name: "image",
                    type: "String",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    default: ExpressionUtils.call("now")
                },
                role: {
                    name: "role",
                    type: "String",
                    optional: true
                },
                banned: {
                    name: "banned",
                    type: "Boolean",
                    optional: true,
                    default: false
                },
                banReason: {
                    name: "banReason",
                    type: "String",
                    optional: true
                },
                banExpires: {
                    name: "banExpires",
                    type: "DateTime",
                    optional: true
                },
                sessions: {
                    name: "sessions",
                    type: "Session",
                    array: true,
                    relation: { opposite: "user" }
                },
                accounts: {
                    name: "accounts",
                    type: "Account",
                    array: true,
                    relation: { opposite: "user" }
                },
                members: {
                    name: "members",
                    type: "Member",
                    array: true,
                    relation: { opposite: "user" }
                },
                invitations: {
                    name: "invitations",
                    type: "Invitation",
                    array: true,
                    relation: { opposite: "user" }
                },
                todoLists: {
                    name: "todoLists",
                    type: "TodoList",
                    array: true,
                    relation: { opposite: "owner" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                email: { type: "String" }
            }
        },
        Session: {
            name: "Session",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true
                },
                expiresAt: {
                    name: "expiresAt",
                    type: "DateTime"
                },
                token: {
                    name: "token",
                    type: "String",
                    unique: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true
                },
                ipAddress: {
                    name: "ipAddress",
                    type: "String",
                    optional: true
                },
                userAgent: {
                    name: "userAgent",
                    type: "String",
                    optional: true
                },
                userId: {
                    name: "userId",
                    type: "String",
                    foreignKeyFor: [
                        "user"
                    ]
                },
                user: {
                    name: "user",
                    type: "User",
                    relation: { opposite: "sessions", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                },
                activeOrganizationId: {
                    name: "activeOrganizationId",
                    type: "String",
                    optional: true
                },
                impersonatedBy: {
                    name: "impersonatedBy",
                    type: "String",
                    optional: true
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                token: { type: "String" }
            }
        },
        Account: {
            name: "Account",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true
                },
                accountId: {
                    name: "accountId",
                    type: "String"
                },
                providerId: {
                    name: "providerId",
                    type: "String"
                },
                userId: {
                    name: "userId",
                    type: "String",
                    foreignKeyFor: [
                        "user"
                    ]
                },
                user: {
                    name: "user",
                    type: "User",
                    relation: { opposite: "accounts", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                },
                accessToken: {
                    name: "accessToken",
                    type: "String",
                    optional: true
                },
                refreshToken: {
                    name: "refreshToken",
                    type: "String",
                    optional: true
                },
                idToken: {
                    name: "idToken",
                    type: "String",
                    optional: true
                },
                accessTokenExpiresAt: {
                    name: "accessTokenExpiresAt",
                    type: "DateTime",
                    optional: true
                },
                refreshTokenExpiresAt: {
                    name: "refreshTokenExpiresAt",
                    type: "DateTime",
                    optional: true
                },
                scope: {
                    name: "scope",
                    type: "String",
                    optional: true
                },
                password: {
                    name: "password",
                    type: "String",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Verification: {
            name: "Verification",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true
                },
                identifier: {
                    name: "identifier",
                    type: "String"
                },
                value: {
                    name: "value",
                    type: "String"
                },
                expiresAt: {
                    name: "expiresAt",
                    type: "DateTime"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    default: ExpressionUtils.call("now")
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Organization: {
            name: "Organization",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true
                },
                name: {
                    name: "name",
                    type: "String"
                },
                slug: {
                    name: "slug",
                    type: "String",
                    unique: true
                },
                logo: {
                    name: "logo",
                    type: "String",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime"
                },
                metadata: {
                    name: "metadata",
                    type: "String",
                    optional: true
                },
                members: {
                    name: "members",
                    type: "Member",
                    array: true,
                    relation: { opposite: "organization" }
                },
                invitations: {
                    name: "invitations",
                    type: "Invitation",
                    array: true,
                    relation: { opposite: "organization" }
                },
                todoLists: {
                    name: "todoLists",
                    type: "TodoList",
                    array: true,
                    relation: { opposite: "organization" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                slug: { type: "String" }
            }
        },
        Member: {
            name: "Member",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true
                },
                organizationId: {
                    name: "organizationId",
                    type: "String",
                    foreignKeyFor: [
                        "organization"
                    ]
                },
                organization: {
                    name: "organization",
                    type: "Organization",
                    relation: { opposite: "members", fields: ["organizationId"], references: ["id"], onDelete: "Cascade" }
                },
                userId: {
                    name: "userId",
                    type: "String",
                    foreignKeyFor: [
                        "user"
                    ]
                },
                user: {
                    name: "user",
                    type: "User",
                    relation: { opposite: "members", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                },
                role: {
                    name: "role",
                    type: "String"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime"
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Invitation: {
            name: "Invitation",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true
                },
                organizationId: {
                    name: "organizationId",
                    type: "String",
                    foreignKeyFor: [
                        "organization"
                    ]
                },
                organization: {
                    name: "organization",
                    type: "Organization",
                    relation: { opposite: "invitations", fields: ["organizationId"], references: ["id"], onDelete: "Cascade" }
                },
                email: {
                    name: "email",
                    type: "String"
                },
                role: {
                    name: "role",
                    type: "String",
                    optional: true
                },
                status: {
                    name: "status",
                    type: "String"
                },
                expiresAt: {
                    name: "expiresAt",
                    type: "DateTime"
                },
                inviterId: {
                    name: "inviterId",
                    type: "String",
                    foreignKeyFor: [
                        "user"
                    ]
                },
                user: {
                    name: "user",
                    type: "User",
                    relation: { opposite: "invitations", fields: ["inviterId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        }
    },
    typeDefs: {
        Auth: {
            name: "Auth",
            fields: {
                userId: {
                    name: "userId",
                    type: "String"
                },
                organizationId: {
                    name: "organizationId",
                    type: "String",
                    optional: true
                },
                organizationRole: {
                    name: "organizationRole",
                    type: "String",
                    optional: true
                }
            },
            attributes: [
                { name: "@@auth" }
            ]
        }
    },
    authType: "Auth",
    plugins: {}
} as const satisfies SchemaDef;
type Schema = typeof _schema & {
    __brand?: "schema";
};
export const schema: Schema = _schema;
export type SchemaType = Schema;
